// Seed deck: single-variable calculus. Every card is a template, so
// the numbers are different on every review. The test suite draws
// each card 100 times and makes the reference answer pass its own
// checker before the deck can ship.

export const deck = {
  id: 'calc1',
  name: 'Single-variable calculus',
  templates: [
    {
      id: 'calc1/power-rule',
      name: 'Power rule',
      skills: ['power rule'],
      par: 25,
      prompt: 'Differentiate. $$f(x) = {{a}}x^{ {{n}} }$$ Find $f\'(x)$.',
      params: {
        a: { type: 'int', min: 2, max: 9 },
        n: { type: 'int', min: 2, max: 6 },
        an: { type: 'computed', expr: 'a*n' },
        nm1: { type: 'computed', expr: 'n-1' },
      },
      answer: { type: 'expression', expr: 'a*n*x^(n-1)', vars: ['x'],
        display: '{{an}}x^{ {{nm1}} }' },
      hints: ['Multiply by the exponent, then lower the exponent by one.'],
      solution: '$$f\'(x) = {{a}}\\cdot{{n}}\\,x^{ {{nm1}} } = {{an}}x^{ {{nm1}} }$$',
    },
    {
      id: 'calc1/chain-sin',
      name: 'Chain rule, sine',
      skills: ['chain rule', 'trig derivatives'],
      par: 30,
      prompt: 'Differentiate. $$f(x) = \\sin({{a}}x)$$',
      params: { a: { type: 'int', min: 2, max: 7 } },
      answer: { type: 'expression', expr: 'a*cos(a*x)', vars: ['x'],
        display: '{{a}}\\cos({{a}}x)' },
      hints: ['Outer derivative first, then multiply by the derivative of the inside.'],
      solution: 'The outside is $\\sin(u)$ and the inside is $u = {{a}}x$, so $f\'(x) = \\cos({{a}}x)\\cdot{{a}}$.',
    },
    {
      id: 'calc1/chain-power',
      name: 'Chain rule, power of a line',
      skills: ['chain rule'],
      par: 40,
      prompt: 'Differentiate. $$f(x) = ({{a}}x + {{b}})^{ {{n}} }$$',
      params: {
        a: { type: 'int', min: 2, max: 5 },
        b: { type: 'int', min: 1, max: 7 },
        n: { type: 'int', min: 3, max: 6 },
        na: { type: 'computed', expr: 'n*a' },
        nm1: { type: 'computed', expr: 'n-1' },
      },
      answer: { type: 'expression', expr: 'n*a*(a*x+b)^(n-1)', vars: ['x'],
        display: '{{na}}({{a}}x + {{b}})^{ {{nm1}} }' },
      hints: ['Treat ${{a}}x + {{b}}$ as the inside function.'],
      solution: '$$f\'(x) = {{n}}({{a}}x+{{b}})^{ {{nm1}} }\\cdot{{a}} = {{na}}({{a}}x + {{b}})^{ {{nm1}} }$$',
    },
    {
      id: 'calc1/product-xe',
      name: 'Product rule with an exponential',
      skills: ['product rule', 'logs and exponentials'],
      par: 70,
      prompt: 'Differentiate. $$f(x) = x^{ {{a}} }e^{ {{b}}x }$$',
      params: {
        a: { type: 'int', min: 2, max: 4 },
        b: { type: 'int', min: 2, max: 5 },
        am1: { type: 'computed', expr: 'a-1' },
      },
      answer: { type: 'expression', expr: 'e^(b*x)*(a*x^(a-1) + b*x^a)', vars: ['x'],
        display: 'e^{ {{b}}x }\\left( {{a}}x^{ {{am1}} } + {{b}}x^{ {{a}} } \\right)' },
      hints: ['Product rule: first times derivative of second, plus second times derivative of first.',
        'Factor $e^{ {{b}}x }$ out of both terms at the end.'],
      solution: '$$f\'(x) = {{a}}x^{ {{am1}} }e^{ {{b}}x } + {{b}}x^{ {{a}} }e^{ {{b}}x } = e^{ {{b}}x }\\left( {{a}}x^{ {{am1}} } + {{b}}x^{ {{a}} } \\right)$$',
    },
    {
      id: 'calc1/quotient-at-point',
      name: 'Quotient rule at a point',
      skills: ['quotient rule'],
      par: 75,
      prompt: 'Let $$f(x) = \\frac{ {{a}}x + {{b}} }{ {{c}}x + {{d}} }$$ Find $f\'(0)$.',
      params: {
        a: { type: 'int', min: 1, max: 6 },
        b: { type: 'int', min: 1, max: 6 },
        c: { type: 'int', min: 1, max: 5 },
        d: { type: 'int', min: 1, max: 5 },
        num: { type: 'computed', expr: 'a*d - b*c' },
        d2: { type: 'computed', expr: 'd^2' },
      },
      nonzero: ['a*d - b*c'],
      answer: { type: 'number', expr: '(a*d - b*c)/d^2',
        display: '\\frac{ {{num}} }{ {{d2}} }' },
      hints: ['Low d-high minus high d-low, over low squared.',
        'You only need the value at $x = 0$, so plug in before simplifying.'],
      solution: '$$f\'(x) = \\frac{ {{a}}({{c}}x+{{d}}) - ({{a}}x+{{b}}){{c}} }{ ({{c}}x + {{d}})^2 }, \\qquad f\'(0) = \\frac{ {{a}}\\cdot{{d}} - {{b}}\\cdot{{c}} }{ {{d}}^2 } = \\frac{ {{num}} }{ {{d2}} }$$',
    },
    {
      id: 'calc1/ln-derivative',
      name: 'Derivative of a logarithm',
      skills: ['logs and exponentials', 'chain rule'],
      par: 35,
      prompt: 'Differentiate. $$f(x) = \\ln({{a}}x + {{b}})$$',
      params: {
        a: { type: 'int', min: 2, max: 6 },
        b: { type: 'int', min: 1, max: 8 },
      },
      answer: { type: 'expression', expr: 'a/(a*x+b)', vars: ['x'], domain: [0, 2],
        display: '\\frac{ {{a}} }{ {{a}}x + {{b}} }' },
      hints: ['$\\frac{d}{dx}\\ln(u) = \\frac{u\'}{u}$.'],
      solution: 'Inside derivative over inside: $$f\'(x) = \\frac{ {{a}} }{ {{a}}x + {{b}} }$$',
    },
    {
      id: 'calc1/tan-derivative',
      name: 'Derivative of tangent',
      skills: ['trig derivatives', 'chain rule'],
      par: 35,
      prompt: 'Differentiate. $$f(x) = \\tan({{a}}x)$$',
      params: { a: { type: 'int', min: 2, max: 5 } },
      answer: { type: 'expression', expr: 'a/cos(a*x)^2', vars: ['x'], domain: [-0.25, 0.25],
        display: '{{a}}\\sec^2({{a}}x)' },
      hints: ['$\\frac{d}{dx}\\tan(u) = \\sec^2(u)\\,u\'$.'],
      solution: '$$f\'(x) = \\sec^2({{a}}x)\\cdot{{a}} = {{a}}\\sec^2({{a}}x)$$ Writing it as $ {{a}}/\\cos^2({{a}}x)$ is the same thing.',
    },
    {
      id: 'calc1/quotient-ln',
      name: 'Quotient rule with a logarithm',
      skills: ['quotient rule', 'logs and exponentials'],
      par: 90,
      prompt: 'Differentiate. $$f(x) = \\frac{ \\ln({{a}}x) }{ x }$$',
      params: { a: { type: 'int', min: 2, max: 5 } },
      answer: { type: 'expression', expr: '(1 - ln(a*x))/x^2', vars: ['x'], domain: [0.4, 3],
        display: '\\frac{ 1 - \\ln({{a}}x) }{ x^2 }' },
      hints: ['$\\frac{d}{dx}\\ln({{a}}x) = \\frac{1}{x}$, the ${{a}}$ cancels.'],
      solution: '$$f\'(x) = \\frac{ \\frac{1}{x}\\cdot x - \\ln({{a}}x)\\cdot 1 }{ x^2 } = \\frac{ 1 - \\ln({{a}}x) }{ x^2 }$$',
    },
    {
      id: 'calc1/second-derivative',
      name: 'Second derivative of a cubic',
      skills: ['power rule'],
      par: 40,
      prompt: 'Let $$f(x) = {{a}}x^3 + {{b}}x^2$$ Find $f\'\'(x)$.',
      params: {
        a: { type: 'int', min: 2, max: 4 },
        b: { type: 'int', min: 2, max: 6 },
        a6: { type: 'computed', expr: '6*a' },
        b2: { type: 'computed', expr: '2*b' },
        a3: { type: 'computed', expr: '3*a' },
      },
      answer: { type: 'expression', expr: '6*a*x + 2*b', vars: ['x'],
        display: '{{a6}}x + {{b2}}' },
      hints: ['Differentiate twice; each pass is just the power rule.'],
      solution: '$$f\'(x) = {{a3}}x^2 + {{b2}}x, \\qquad f\'\'(x) = {{a6}}x + {{b2}}$$',
    },
    {
      id: 'calc1/tangent-slope',
      name: 'Slope of a tangent line',
      skills: ['tangent lines', 'power rule'],
      par: 45,
      prompt: 'Find the slope of the tangent line to $y = x^2 {{a:+}}x$ at $x = {{b}}$.',
      params: {
        a: { type: 'int', min: 2, max: 8 },
        b: { type: 'int', min: 1, max: 4 },
        m: { type: 'computed', expr: '2*b + a' },
      },
      answer: { type: 'number', expr: '2*b + a', display: '{{m}}' },
      hints: ['The slope of the tangent is the derivative evaluated at that point.'],
      solution: '$y\' = 2x {{a:+}}$, and at $x = {{b}}$ that is $2\\cdot{{b}} {{a:+}} = {{m}}$.',
    },
    {
      id: 'calc1/vertex',
      name: 'Minimum of a parabola',
      skills: ['optimization', 'power rule'],
      par: 50,
      prompt: 'Let $$f(x) = {{p}}x^2 {{q:+}}x + {{r}}$$ Find the value of $x$ where $f$ is smallest.',
      params: {
        p: { type: 'int', min: 2, max: 4 },
        q: { type: 'int', min: -8, max: 8, ne: [0] },
        r: { type: 'int', min: 1, max: 5 },
        p2: { type: 'computed', expr: '2*p' },
      },
      answer: { type: 'number', expr: '-q/(2*p)', display: '-\\frac{ {{q}} }{ {{p2}} }' },
      hints: ['Set $f\'(x) = 0$ and solve. Fractions are fine as answers.'],
      solution: '$f\'(x) = {{p2}}x {{q:+}} = 0$ gives $x = -\\frac{ {{q}} }{ {{p2}} }$. The parabola opens upward, so this is the minimum.',
    },
    {
      id: 'calc1/limit-factor',
      name: 'Limit by factoring',
      skills: ['limits'],
      par: 45,
      prompt: 'Evaluate. $$\\lim_{x \\to {{a}} } \\frac{ x^2 - {{a2}} }{ x - {{a}} }$$',
      params: {
        a: { type: 'int', min: 2, max: 7 },
        a2: { type: 'computed', expr: 'a^2' },
        twoa: { type: 'computed', expr: '2*a' },
      },
      answer: { type: 'number', expr: '2*a', display: '{{twoa}}' },
      hints: ['The numerator is a difference of squares.'],
      solution: '$$\\frac{ x^2 - {{a2}} }{ x - {{a}} } = \\frac{ (x-{{a}})(x+{{a}}) }{ x - {{a}} } = x + {{a}} \\;\\longrightarrow\\; {{twoa}}$$',
    },
    {
      id: 'calc1/limit-sin',
      name: 'Small-angle limit',
      skills: ['limits'],
      par: 30,
      prompt: 'Evaluate. $$\\lim_{x \\to 0} \\frac{ \\sin({{a}}x) }{ x }$$',
      params: { a: { type: 'int', min: 2, max: 8 } },
      answer: { type: 'number', expr: 'a', display: '{{a}}' },
      hints: ['Rescale so it looks like $\\sin(u)/u$.'],
      solution: '$$\\frac{ \\sin({{a}}x) }{ x } = {{a}}\\cdot\\frac{ \\sin({{a}}x) }{ {{a}}x } \\;\\longrightarrow\\; {{a}}\\cdot 1 = {{a}}$$',
    },
    {
      id: 'calc1/limit-exp',
      name: 'Exponential limit',
      skills: ['limits', 'logs and exponentials'],
      par: 40,
      prompt: 'Evaluate. $$\\lim_{x \\to 0} \\frac{ e^{ {{a}}x } - 1 }{ x }$$',
      params: { a: { type: 'int', min: 2, max: 7 } },
      answer: { type: 'number', expr: 'a', display: '{{a}}' },
      hints: ['This is the definition of a derivative at $0$ in disguise.'],
      solution: 'It is the derivative of $e^{ {{a}}x }$ at $x=0$, which is $ {{a}}e^0 = {{a}}$. L\'Hopital gives the same thing.',
    },
    {
      id: 'calc1/reverse-power',
      name: 'Antiderivative of a power of a line',
      skills: ['antiderivatives', 'u-substitution'],
      par: 60,
      prompt: 'Integrate. $$\\int ({{a}}x + {{b}})^{ {{n}} }\\,dx$$',
      params: {
        a: { type: 'int', min: 2, max: 4 },
        b: { type: 'int', min: 1, max: 6 },
        n: { type: 'int', min: 2, max: 4 },
        np1: { type: 'computed', expr: 'n+1' },
        anp1: { type: 'computed', expr: 'a*(n+1)' },
      },
      answer: { type: 'expression', expr: '(a*x+b)^(n+1)/(a*(n+1))', vars: ['x'],
        upToConstant: true,
        display: '\\frac{ ({{a}}x + {{b}})^{ {{np1}} } }{ {{anp1}} } + C' },
      hints: ['Substitute $u = {{a}}x + {{b}}$, so $du = {{a}}\\,dx$.'],
      solution: 'With $u = {{a}}x+{{b}}$: $$\\int u^{ {{n}} }\\,\\frac{du}{ {{a}} } = \\frac{ u^{ {{np1}} } }{ {{anp1}} } + C = \\frac{ ({{a}}x + {{b}})^{ {{np1}} } }{ {{anp1}} } + C$$',
    },
    {
      id: 'calc1/int-cos',
      name: 'Antiderivative of cosine',
      skills: ['antiderivatives', 'trig derivatives'],
      par: 35,
      prompt: 'Integrate. $$\\int \\cos({{a}}x)\\,dx$$',
      params: { a: { type: 'int', min: 2, max: 6 } },
      answer: { type: 'expression', expr: 'sin(a*x)/a', vars: ['x'], upToConstant: true,
        display: '\\frac{ \\sin({{a}}x) }{ {{a}} } + C' },
      hints: ['Differentiate your guess; a stray factor of ${{a}}$ tells you what to divide by.'],
      solution: '$$\\int \\cos({{a}}x)\\,dx = \\frac{ \\sin({{a}}x) }{ {{a}} } + C$$ Check: differentiating brings the ${{a}}$ back down.',
    },
    {
      id: 'calc1/u-sub-xe',
      name: 'u-substitution with an exponential',
      skills: ['u-substitution'],
      par: 75,
      prompt: 'Integrate. $$\\int x\\,e^{ {{a}}x^2 }\\,dx$$',
      params: {
        a: { type: 'int', min: 2, max: 5 },
        a2: { type: 'computed', expr: '2*a' },
      },
      answer: { type: 'expression', expr: 'e^(a*x^2)/(2*a)', vars: ['x'],
        domain: [-1.2, 1.2], upToConstant: true,
        display: '\\frac{ e^{ {{a}}x^2 } }{ {{a2}} } + C' },
      hints: ['Substitute $u = {{a}}x^2$. The stray $x$ is exactly what $du$ needs.'],
      solution: 'With $u = {{a}}x^2$, $du = {{a2}}x\\,dx$: $$\\int \\frac{ e^u }{ {{a2}} }\\,du = \\frac{ e^{ {{a}}x^2 } }{ {{a2}} } + C$$',
    },
    {
      id: 'calc1/parts-xe',
      name: 'Integration by parts, exponential',
      skills: ['integration by parts'],
      par: 90,
      prompt: 'Integrate. $$\\int x\\,e^{ {{a}}x }\\,dx$$',
      params: {
        a: { type: 'int', min: 2, max: 4 },
        asq: { type: 'computed', expr: 'a^2' },
      },
      answer: { type: 'expression', expr: 'e^(a*x)*(x/a - 1/a^2)', vars: ['x'],
        domain: [-2, 2], upToConstant: true,
        display: '\\frac{ x\\,e^{ {{a}}x } }{ {{a}} } - \\frac{ e^{ {{a}}x } }{ {{asq}} } + C' },
      hints: ['Parts with $u = x$, $dv = e^{ {{a}}x }dx$.'],
      solution: '$$\\int x\\,e^{ {{a}}x }\\,dx = \\frac{ x\\,e^{ {{a}}x } }{ {{a}} } - \\int \\frac{ e^{ {{a}}x } }{ {{a}} }\\,dx = \\frac{ x\\,e^{ {{a}}x } }{ {{a}} } - \\frac{ e^{ {{a}}x } }{ {{asq}} } + C$$',
    },
    {
      id: 'calc1/parts-xcos',
      name: 'Integration by parts, cosine',
      skills: ['integration by parts', 'trig derivatives'],
      par: 90,
      prompt: 'Integrate. $$\\int x\\cos({{a}}x)\\,dx$$',
      params: {
        a: { type: 'int', min: 2, max: 4 },
        asq: { type: 'computed', expr: 'a^2' },
      },
      answer: { type: 'expression', expr: 'x*sin(a*x)/a + cos(a*x)/a^2', vars: ['x'],
        upToConstant: true,
        display: '\\frac{ x\\sin({{a}}x) }{ {{a}} } + \\frac{ \\cos({{a}}x) }{ {{asq}} } + C' },
      hints: ['Parts with $u = x$, $dv = \\cos({{a}}x)dx$.'],
      solution: '$$\\int x\\cos({{a}}x)\\,dx = \\frac{ x\\sin({{a}}x) }{ {{a}} } - \\int \\frac{ \\sin({{a}}x) }{ {{a}} }\\,dx = \\frac{ x\\sin({{a}}x) }{ {{a}} } + \\frac{ \\cos({{a}}x) }{ {{asq}} } + C$$',
    },
    {
      id: 'calc1/definite-power',
      name: 'Definite integral of a power',
      skills: ['definite integrals', 'antiderivatives'],
      par: 55,
      prompt: 'Evaluate. $$\\int_0^{ {{b}} } x^{ {{n}} }\\,dx$$',
      params: {
        b: { type: 'int', min: 2, max: 4 },
        n: { type: 'int', min: 2, max: 4 },
        np1: { type: 'computed', expr: 'n+1' },
      },
      answer: { type: 'number', expr: 'b^(n+1)/(n+1)',
        display: '\\frac{ {{b}}^{ {{np1}} } }{ {{np1}} }' },
      hints: ['Antidifferentiate, then evaluate at the endpoints.'],
      solution: '$$\\int_0^{ {{b}} } x^{ {{n}} }\\,dx = \\left[ \\frac{ x^{ {{np1}} } }{ {{np1}} } \\right]_0^{ {{b}} } = \\frac{ {{b}}^{ {{np1}} } }{ {{np1}} }$$',
    },
    {
      id: 'calc1/definite-cos',
      name: 'Definite integral of cosine',
      skills: ['definite integrals', 'exact trig values'],
      par: 65,
      prompt: 'Evaluate. $$\\int_0^{ \\pi / {{a2}} } \\cos({{a}}x)\\,dx$$',
      params: {
        a: { type: 'int', min: 2, max: 4 },
        a2: { type: 'computed', expr: '2*a' },
      },
      answer: { type: 'number', expr: '1/a', display: '\\frac{1}{ {{a}} }' },
      hints: ['The antiderivative is $\\sin({{a}}x)/{{a}}$; the upper limit lands on $\\sin(\\pi/2)$.'],
      solution: '$$\\left[ \\frac{ \\sin({{a}}x) }{ {{a}} } \\right]_0^{ \\pi/{{a2}} } = \\frac{ \\sin(\\pi/2) }{ {{a}} } - 0 = \\frac{1}{ {{a}} }$$',
    },
    {
      id: 'calc1/trig-recall',
      name: 'Exact trig values',
      skills: ['exact trig values'],
      par: 15,
      prompt: 'Evaluate exactly. $${{q.fn}}\\!\\left( {{q.ang}} \\right)$$',
      params: {
        q: { type: 'pick', from: [
          { fn: '\\sin', ang: '\\frac{\\pi}{6}', val: '1/2', show: '\\tfrac{1}{2}' },
          { fn: '\\sin', ang: '\\frac{\\pi}{4}', val: 'sqrt(2)/2', show: '\\tfrac{\\sqrt{2}}{2}' },
          { fn: '\\sin', ang: '\\frac{\\pi}{3}', val: 'sqrt(3)/2', show: '\\tfrac{\\sqrt{3}}{2}' },
          { fn: '\\cos', ang: '\\frac{\\pi}{6}', val: 'sqrt(3)/2', show: '\\tfrac{\\sqrt{3}}{2}' },
          { fn: '\\cos', ang: '\\frac{\\pi}{4}', val: 'sqrt(2)/2', show: '\\tfrac{\\sqrt{2}}{2}' },
          { fn: '\\cos', ang: '\\frac{\\pi}{3}', val: '1/2', show: '\\tfrac{1}{2}' },
          { fn: '\\tan', ang: '\\frac{\\pi}{6}', val: '1/sqrt(3)', show: '\\tfrac{1}{\\sqrt{3}}' },
          { fn: '\\tan', ang: '\\frac{\\pi}{4}', val: '1', show: '1' },
          { fn: '\\tan', ang: '\\frac{\\pi}{3}', val: 'sqrt(3)', show: '\\sqrt{3}' },
        ] },
      },
      answer: { type: 'number', expr: '{{q.val}}', display: '{{q.show}}' },
      hints: ['Sketch the 30-60-90 or 45-45-90 triangle.'],
      solution: 'From the special triangles: $${{q.fn}}\\!\\left( {{q.ang}} \\right) = {{q.show}}$$ Typing 1/2 or sqrt(3)/2 both work; so does a decimal.',
    },
  ],
};
