// Seed deck: how to study. The techniques the app is built on, taught
// through the app itself. Prose cards: cloze prompts hide a different
// span each review, typed answers get a little typo room, explain-back
// cards are graded by you.

export const deck = {
  id: 'techniques',
  name: 'How to study',
  templates: [
    {
      id: 'techniques/retrieval-vs-rereading',
      name: 'Why rereading feels better than it works',
      skills: ['active recall'],
      par: 30,
      prompt: 'Rereading notes feels productive because the text becomes familiar, but familiarity is not [[retrieval]]. Pulling a memory back out is what strengthens it, and rereading never makes you pull.',
      answer: { type: 'cloze' },
      hints: ['The r-word for getting a memory back out of your head.'],
      solution: 'This is the testing effect: the act of retrieving a memory strengthens it far more than re-exposing yourself to it.',
    },
    {
      id: 'techniques/testing-effect',
      name: 'The strongest studying move',
      skills: ['active recall'],
      par: 25,
      prompt: 'Across controlled comparisons, one technique beats rereading for long-term retention again and again. What is it called?',
      answer: { type: 'text', accept: ['retrieval practice', 'practice testing', 'testing', 'self testing', 'active recall', 'testing yourself'] },
      hints: ['You are doing it right now.'],
      solution: 'Retrieval practice, also called the testing effect. Closed-book recall beats another pass over the notes.',
    },
    {
      id: 'techniques/roediger-karpicke',
      name: 'The 2006 experiments',
      skills: ['active recall', 'memory science'],
      par: 35,
      prompt: 'In Roediger and Karpicke\'s 2006 experiments, students who took practice [[tests]] remembered far more a week later than students who spent the same time [[rereading]], even though the rereaders felt more confident.',
      answer: { type: 'cloze' },
      hints: ['One group quizzed themselves, the other group did the default thing.'],
      solution: 'A week out, the tested group retained dramatically more. The rereaders predicted they would do better and were wrong, which is why feelings are a bad study meter.',
    },
    {
      id: 'techniques/spacing-effect',
      name: 'The spacing effect',
      skills: ['spaced repetition'],
      par: 25,
      prompt: 'The [[spacing]] effect: the same number of reviews produces much stronger memory when they are spread over days instead of massed into one sitting.',
      answer: { type: 'cloze' },
      hints: ['The opposite of cramming.'],
      solution: 'Spreading reviews out forces each one to happen when the memory is partly faded, and effortful recall is what builds durable storage.',
    },
    {
      id: 'techniques/forgetting-curve',
      name: 'Ebbinghaus and the curve',
      skills: ['spaced repetition', 'memory science'],
      par: 30,
      prompt: 'Ebbinghaus mapped the [[forgetting]] curve in 1885: memory decays fastest right after learning, and each successful review flattens the curve.',
      answer: { type: 'cloze' },
      hints: ['The curve is about what happens to memories you leave alone.'],
      solution: 'The schedule this app runs is built directly on that curve: it asks for a card near the moment you would otherwise lose it.',
    },
    {
      id: 'techniques/interleaving',
      name: 'Mixing beats blocking',
      skills: ['interleaving'],
      par: 30,
      prompt: 'Practicing different problem types shuffled together is called [[interleaving]]. It feels slower than doing twenty of the same problem in a row, and it wins on exams.',
      answer: { type: 'cloze' },
      hints: ['The word for shuffling topics inside one session.'],
      solution: 'Blocked practice lets you stop deciding which method to use; the shuffle keeps that decision alive, and the decision is the exam skill.',
    },
    {
      id: 'techniques/why-interleave',
      name: 'Why interleaving wins',
      skills: ['interleaving'],
      par: 30,
      prompt: 'Why does interleaved practice beat blocked practice on exams?',
      answer: {
        type: 'choice',
        options: [
          'Exams mix problem types, so picking the right method is itself the skill to train',
          'It lets you get through more problems per hour',
          'Doing easy runs of one type builds confidence first',
          'Repeating one type causes mental fatigue',
        ],
        correct: 0,
      },
      hints: ['Think about what a mixed exam asks you to do before any algebra starts.'],
      solution: 'On an exam nothing announces which technique a problem wants. Blocked practice trains execution; interleaving trains recognition plus execution.',
    },
    {
      id: 'techniques/desirable-difficulty',
      name: 'Desirable difficulties',
      skills: ['memory science'],
      par: 25,
      prompt: 'Bjork\'s name for the paradox that harder, slower practice produces stronger learning: [[desirable]] difficulties.',
      answer: { type: 'cloze' },
      hints: ['The difficulty is not a bug, it is a ...'],
      solution: 'If studying feels easy, it is probably not doing much. Struggling to recall, mixing topics, and spacing reviews all hurt in the moment and pay later.',
    },
    {
      id: 'techniques/dunlosky-ranking',
      name: 'What the review of reviews found',
      skills: ['active recall', 'memory science'],
      par: 30,
      prompt: 'Dunlosky\'s 2013 review of study techniques put highlighting and rereading near the [[bottom]] of the ranking, and practice testing plus spaced practice at the [[top]].',
      answer: { type: 'cloze' },
      hints: ['The most popular techniques and the most effective ones are not the same list.'],
      solution: 'The two big winners are exactly the two things a session here does: retrieval, on a spaced schedule.',
    },
    {
      id: 'techniques/feynman',
      name: 'The Feynman technique',
      skills: ['active recall', 'understanding'],
      par: 90,
      prompt: 'From memory: walk through the Feynman technique, all four steps.',
      answer: { type: 'self' },
      hints: ['It starts with a blank page and a concept name.'],
      solution: 'Pick a concept and write its name at the top. Explain it in plain words, as if teaching someone new to it. Notice where the explanation breaks or leans on jargon: those are your gaps. Go back to the source to fill them, then simplify again, ideally with an analogy. The breaks are the whole point; the technique is a gap detector.',
    },
    {
      id: 'techniques/pomodoro',
      name: 'The pomodoro rhythm',
      skills: ['focus'],
      par: 20,
      prompt: 'The classic pomodoro rhythm: how many minutes of focused work before each short break?',
      answer: { type: 'text', accept: ['25', '25 minutes', 'twenty five', 'twenty-five'] },
      hints: ['A kitchen timer shaped like a tomato.'],
      solution: 'Cirillo\'s original recipe is 25 minutes on, about 5 off, with a longer break every four rounds. The exact numbers matter less than the contract: while the timer runs, only the work exists.',
    },
    {
      id: 'techniques/sleep',
      name: 'Where consolidation happens',
      skills: ['memory science', 'focus'],
      par: 25,
      prompt: 'Memory consolidation happens largely during [[sleep]]; an all-nighter trades away the step where studying becomes permanent.',
      answer: { type: 'cloze' },
      hints: ['The step you cannot do at a desk.'],
      solution: 'The night after learning is when the brain replays and stabilizes new memories. Staying up to cram borrows those hours from the process that was going to save the material.',
    },
    {
      id: 'techniques/confidence',
      name: 'Why this app does not ask how it felt',
      skills: ['memory science', 'active recall'],
      par: 30,
      prompt: 'This app grades from what actually happened instead of asking how the review felt, because self-rated [[confidence]] is a poor predictor of later recall.',
      answer: { type: 'cloze' },
      hints: ['The thing rereaders have lots of, wrongly.'],
      solution: 'Judgments of learning are systematically miscalibrated: fluent-feeling material feels known. Timing and correctness are honest; feelings are not.',
    },
    {
      id: 'techniques/exam-night',
      name: 'The night-before plan',
      skills: ['active recall', 'interleaving', 'focus'],
      par: 90,
      prompt: 'From memory: design the last two hours of studying before a problem-heavy exam. What fills the time, and what is banned?',
      answer: { type: 'self' },
      hints: ['Almost none of it is reading.'],
      solution: 'Work problems closed-book, mixed across topics, checking each answer right after. Open the notes only to patch a specific gap a miss exposed, then close them again. Short breaks on a timer. Banned: rereading chapters, recopying notes, highlighting, and trading sleep for one more pass.',
    },
  ],
};
